#
# Copyright (C) 2012-2013, Guennadi Liakhovetski <lg@denx.de>
# (C) Copyright 2012-2013 Freescale Semiconductor, Inc.
# Copyright (C) 2013, Boundary Devices <info@boundarydevices.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

#CFLAGS += -g3 -O0

#obj-y  := e20.o dp83848_mxc.o
obj-y  := e20.o 
